dist: focal

language: c++

cache: apt

sudo: false

addons:
  apt:
    packages:
      - libwxgtk3.0-gtk3-dev libbluetooth-dev libxml2-dev libusb-1.0-0-dev libncursesw5-dev gettext libmhash-dev libcurl4-gnutls-dev libxi-dev libx11-dev

compiler:
  - gcc

script: make
